impl: 'https://github.com/mlengse/tracks/raw/main'
repo: https://pkg-repo.blendos.co

track: 'dev-kde'

packages:
  - 'grub-customizer'
  - 'fontconfig'
  - 'curl'
  - 'libxkbcommon-x11'
  - 'nss'
  - 'python-virtualenv'
  - 'xcb-util-cursor'
  - 'xcb-util-keysyms'
  - 'xcb-util-wm'
  - 'xz'
  # - 'kde-utilities-meta'
  # - 'plasma'
  # - 'plasma-workspace'
  # - 'sddm'
  # - 'waydroid'
  # - 'waydroid-image'

# services:
  # - 'sddm'

commands:
  # - 'rm -f /usr/share/applications/Waydroid.desktop'
  - 'curl -L https://raw.githubusercontent.com/sebanc/linuxloops/main/linuxloops -O /bin'
  - 'chmod -x /bin/linuxloops'
  - 'curl -fsSL https://bun.sh/install | bash'
