impl: 'https://github.com/mlengse/tracks/raw/main'
repo: https://pkg-repo.blendos.co

track: 'blendos-base'

packages:
  - 'unzip'
  - 'curl'
  - 'kde-system-meta'
  - 'kde-utilities-meta'
  - 'plasma'
  - 'plasma-workspace'
  - 'sddm'
  - 'xorg'
  - 'fontconfig'
  - 'libxkbcommon-x11'
  - 'nss'
  - 'python-virtualenv'
  - 'xcb-util-cursor'
  - 'xcb-util-keysyms'
  - 'xcb-util-wm'
  - 'xz'
  - 'grub-customizer'
  - 'vscodium'
  - 'chaotic-aur/waydroid'
  - 'chaotic-aur/python-gbinder'
  - 'chaotic-aur/waydroid-image-gapps'
  - 'chaotic-aur/bun'
  - 'chaotic-aur/nvm'
  # - 'kde-utilities-meta'
  # - 'plasma'
  # - 'plasma-workspace'
  # - 'sddm'
  # - 'waydroid'
  # - 'waydroid-image'

services:
  - 'sddm'

package-repos:
  - name: 'chaotic-aur'
    repo-url: 'https://cdn-mirror.chaotic.cx/$repo/$arch'

commands:
  - 'locale-gen'
  - 'rm -f /usr/share/applications/Waydroid.desktop'
  # - 'curl -L https://raw.githubusercontent.com/sebanc/linuxloops/main/linuxloops -O /bin'
  # - 'chmod -x /bin/linuxloops'
  # - 'curl -fsSL https://bun.sh/install | bash'
  # - 'waydroid init -s GAPPS'
